name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: release

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          release-type: node

  publish:
    name: Publish image
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    needs: release-please
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release tag name
        run: |
          full_tag_name="${{ needs.release-please.outputs.tag_name }}"
          tag_name=${full_tag_name#v}
          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/tofuuudon/shipmate:${{ env.TAG_NAME }}
            ghcr.io/tofuuudon/shipmate:latest
